name: BlacklistItems
main: me.noeffort.blacklistitems.Main
version: 0.3.8

depends: [mcMMO]
description: Stop the usage of repairable items in mcMMO and anvils
author: NoEffort 

commands:
  blacklist:
    aliases: bl
    description: Blacklist items
    usage: "Usage: /<command> [metadata]"